pdf_texts_dir: ../data/pdf_texts
vectorstore:
  path: ../faiss_index
embedding:
  model: cambridgeltl/SapBERT-UMLS-2020AB-all-lang-from-XLMR
llm:
  backend: cuda
  model: ollama/deepseek/r1:8b
  url: http://localhost:11434
ui:
  host: 0.0.0.0
  port: 7860