pdf_texts_dir: ../data/pdf_texts
vectorstore:
  type: chroma
  path: ../chroma_db
embedding:
  model: cambridgeltl/SapBERT-from-PubMedBERT-fulltext
llm:
  backend: cuda
  model: ollama/deepseek/r1:8b
  url: http://localhost:11434
ui:
  host: 0.0.0.0
  port: 7860